### PR TITLE
Added hashing of passwords for its storage in the database

### PR DESCRIPTION
**Pull request by himanshukumar660**
Hey @yochannah . Just added a hashing mechanism so that the password could be stored in its hashed form rather than a plain text. Please review it and suggest any modification, if any. Thanks :)

### CODE REVIEW

**Comment by himanshukumar660** [comment]
Have you tried running the mongodb server.

**Comment by himanshukumar660** [comment]
I think this issue has been addressed and solved [here](https://github.com/kelektiv/node.bcrypt.js/issues/656#issuecomment-427372239)

**Comment by yochannah** [comment]
@himanshukumar660 thanks, changing it to version 3.0.0 fixed the issue. Could you update package.json in your PR to specify 3.0.0?

**Comment by himanshukumar660** [comment]
@yochannah Please Check if everything is fine.

**Comment by yochannah** [comment]
@himanshukumar660 you were right - the bcrypt version rollback fixed things. 

I think we still need a tweak to `initRegistry.js`, though - now, in order to run it I need to paste the hashed password into the password field, not the plaintext.

**Comment by himanshukumar660** [comment]
@yochannah Uncommited last 3 commits because I had to change the entire logic. This commit solves the problem related to the tweak required for running `initRegistry.js` correctly.

**Comment by yochannah** [comment]
@himanshukumar660 this is looking good! There is one small bit that needs to be fixed, but otherwise everything I tested worked nicely. 

1. pull code from your fork, dev branch
2. `node createUser.js` >> all worked! :+1: 
   - [x] The password is hashed when I check in mongo!
3. Started the server with `npm start` and ran some checks: 
   - [x] successfully logged in with the password and user from step 2 :tada: 
   - [x] deleted an instance successfully
   - [x] tried to press the yellow synchronise all button (bottom right) - this gives a popup asking for re-auth, 
image but does work. I'd prefer no pop-up but that's not a big thing. Oddly, it didn't ask for this the next time I tried it...

   - [ ] tried to add instance. :crying_cat_face:  This caused the server to error out and stop running:
   - [ ] tried to update. This also failed, I assume for the same reason the ass instance didn't work. Stack trace: 

```bash
POST /service/instances 401 64.820 ms - -
undefined:1
Unauthorized
^

SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/FILESERVER5/micklem/yy406/projects/intermine-registry/routes/index.js:216:21)
    at Request.self.callback (/home/FILESERVER5/micklem/yy406/projects/intermine-registry/node_modules/request/request.js:186:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/FILESERVER5/micklem/yy406/projects/intermine-registry/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/FILESERVER5/micklem/yy406/projects/intermine-registry/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! registryapp@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the registryapp@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by yochannah** [comment]
apparently this is working nicely on @himanshukumar660's computer :laughing: it might be handy to have someone else try this out as well.

**Comment by yochannah** [comment]
okay, it's all working nicely now - thanks so much @himanshukumar660 for all your hard work on this - it's been a bit of a journey getting there! :trophy:

**Comment by yochannah** [comment]
One small comment might be to try avoiding force-pushes in the future if possible. Even so, nice job :)

**Pull request merged**
